# Generated by Django 4.1.4 on 2022-12-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internfair", "0004_students_transactionid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="transactionId",
            field=models.CharField(default="", max_length=150),
        ),
    ]
