# Generated by Django 4.1.4 on 2022-12-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internfair", "0005_alter_students_transactionid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="transactionId",
        ),
    ]
